# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiPostulantesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, apellidos: str=None, dni: str=None, email: str=None, estado: str=None, fecha_nacimiento: str=None, nombres: str=None):  # noqa: E501
        """ApiPostulantesBody - a model defined in Swagger

        :param apellidos: The apellidos of this ApiPostulantesBody.  # noqa: E501
        :type apellidos: str
        :param dni: The dni of this ApiPostulantesBody.  # noqa: E501
        :type dni: str
        :param email: The email of this ApiPostulantesBody.  # noqa: E501
        :type email: str
        :param estado: The estado of this ApiPostulantesBody.  # noqa: E501
        :type estado: str
        :param fecha_nacimiento: The fecha_nacimiento of this ApiPostulantesBody.  # noqa: E501
        :type fecha_nacimiento: str
        :param nombres: The nombres of this ApiPostulantesBody.  # noqa: E501
        :type nombres: str
        """
        self.swagger_types = {
            'apellidos': str,
            'dni': str,
            'email': str,
            'estado': str,
            'fecha_nacimiento': str,
            'nombres': str
        }

        self.attribute_map = {
            'apellidos': 'apellidos',
            'dni': 'dni',
            'email': 'email',
            'estado': 'estado',
            'fecha_nacimiento': 'fecha_nacimiento',
            'nombres': 'nombres'
        }
        self._apellidos = apellidos
        self._dni = dni
        self._email = email
        self._estado = estado
        self._fecha_nacimiento = fecha_nacimiento
        self._nombres = nombres

    @classmethod
    def from_dict(cls, dikt) -> 'ApiPostulantesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_postulantes_body of this ApiPostulantesBody.  # noqa: E501
        :rtype: ApiPostulantesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def apellidos(self) -> str:
        """Gets the apellidos of this ApiPostulantesBody.


        :return: The apellidos of this ApiPostulantesBody.
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos: str):
        """Sets the apellidos of this ApiPostulantesBody.


        :param apellidos: The apellidos of this ApiPostulantesBody.
        :type apellidos: str
        """

        self._apellidos = apellidos

    @property
    def dni(self) -> str:
        """Gets the dni of this ApiPostulantesBody.


        :return: The dni of this ApiPostulantesBody.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """Sets the dni of this ApiPostulantesBody.


        :param dni: The dni of this ApiPostulantesBody.
        :type dni: str
        """

        self._dni = dni

    @property
    def email(self) -> str:
        """Gets the email of this ApiPostulantesBody.


        :return: The email of this ApiPostulantesBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ApiPostulantesBody.


        :param email: The email of this ApiPostulantesBody.
        :type email: str
        """

        self._email = email

    @property
    def estado(self) -> str:
        """Gets the estado of this ApiPostulantesBody.


        :return: The estado of this ApiPostulantesBody.
        :rtype: str
        """
        return self._estado

    @estado.setter
    def estado(self, estado: str):
        """Sets the estado of this ApiPostulantesBody.


        :param estado: The estado of this ApiPostulantesBody.
        :type estado: str
        """

        self._estado = estado

    @property
    def fecha_nacimiento(self) -> str:
        """Gets the fecha_nacimiento of this ApiPostulantesBody.


        :return: The fecha_nacimiento of this ApiPostulantesBody.
        :rtype: str
        """
        return self._fecha_nacimiento

    @fecha_nacimiento.setter
    def fecha_nacimiento(self, fecha_nacimiento: str):
        """Sets the fecha_nacimiento of this ApiPostulantesBody.


        :param fecha_nacimiento: The fecha_nacimiento of this ApiPostulantesBody.
        :type fecha_nacimiento: str
        """

        self._fecha_nacimiento = fecha_nacimiento

    @property
    def nombres(self) -> str:
        """Gets the nombres of this ApiPostulantesBody.


        :return: The nombres of this ApiPostulantesBody.
        :rtype: str
        """
        return self._nombres

    @nombres.setter
    def nombres(self, nombres: str):
        """Sets the nombres of this ApiPostulantesBody.


        :param nombres: The nombres of this ApiPostulantesBody.
        :type nombres: str
        """

        self._nombres = nombres
