# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PostulantesValidardocumentosBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, postulante_id: str=None):  # noqa: E501
        """PostulantesValidardocumentosBody - a model defined in Swagger

        :param postulante_id: The postulante_id of this PostulantesValidardocumentosBody.  # noqa: E501
        :type postulante_id: str
        """
        self.swagger_types = {
            'postulante_id': str
        }

        self.attribute_map = {
            'postulante_id': 'postulante_id'
        }
        self._postulante_id = postulante_id

    @classmethod
    def from_dict(cls, dikt) -> 'PostulantesValidardocumentosBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postulantes_validardocumentos_body of this PostulantesValidardocumentosBody.  # noqa: E501
        :rtype: PostulantesValidardocumentosBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def postulante_id(self) -> str:
        """Gets the postulante_id of this PostulantesValidardocumentosBody.


        :return: The postulante_id of this PostulantesValidardocumentosBody.
        :rtype: str
        """
        return self._postulante_id

    @postulante_id.setter
    def postulante_id(self, postulante_id: str):
        """Sets the postulante_id of this PostulantesValidardocumentosBody.


        :param postulante_id: The postulante_id of this PostulantesValidardocumentosBody.
        :type postulante_id: str
        """

        self._postulante_id = postulante_id
