openapi: 3.0.3
info:
  title: Postulante - Pruebas BDD
  contact: {}
  version: 1.0.0
servers:
- url: http://127.0.0.1
tags:
- name: Crear Postulante
- name: PublicarResultado
- name: ValidarDocumentos
paths:
  /api/postulantes/:
    post:
      tags:
      - Crear Postulante
      summary: New Request
      description: New Request
      operationId: new_request
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api_postulantes_body"
            example:
              apellidos: Pérez
              dni: "74863621"
              email: juan@example.com
              estado: pendiente
              fecha_nacimiento: 2000-01-01
              nombres: Juan
      responses:
        "200":
          description: ""
      x-openapi-router-controller: swagger_server.controllers.crear_postulante_controller
  /api/resultados/:
    post:
      tags:
      - PublicarResultado
      summary: New Request
      description: New Request
      operationId: new_request1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api_resultados_body"
            example:
              aprobado: true
              comentario: Buen rendimiento
              postulante_id: "3"
              puntaje: 89.5
      responses:
        "200":
          description: ""
      x-openapi-router-controller: swagger_server.controllers.publicar_resultado_controller
  /api/postulantes/validar-documentos/:
    post:
      tags:
      - ValidarDocumentos
      summary: New Request
      description: New Request
      operationId: new_request2
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postulantes_validardocumentos_body"
            example:
              postulante_id: "7"
      responses:
        "200":
          description: ""
      x-openapi-router-controller: swagger_server.controllers.validar_documentos_controller
components:
  schemas:
    api_postulantes_body:
      type: object
      properties:
        apellidos:
          type: string
          example: Pérez
        dni:
          type: string
          example: "74863621"
        email:
          type: string
          example: juan@example.com
        estado:
          type: string
          example: pendiente
        fecha_nacimiento:
          type: string
          example: 2000-01-01
        nombres:
          type: string
          example: Juan
    api_resultados_body:
      type: object
      properties:
        aprobado:
          type: boolean
          example: true
        comentario:
          type: string
          example: Buen rendimiento
        postulante_id:
          type: string
          example: "3"
        puntaje:
          type: number
          example: 89.5
    postulantes_validardocumentos_body:
      type: object
      properties:
        postulante_id:
          type: string
          example: "7"

